Prueba GIT ACTIONS

diff --git a/.github/workflows/maven_deploy.yml b/.github/workflows/maven_deploy.yml
--- a/.github/workflows/maven_deploy.yml
+++ b/.github/workflows/maven_deploy.yml
@@ -19,11 +19,21 @@ jobs:
           distribution: 'temurin'
           architecture: x64
 
-      - name: Setting enviroments
-        run: echo "Setting enviroments"          
+      - name: Set environment variables
         env:
           OYM_USERNAME: ${{ secrets.OYM_USERNAME }}
           OYM_PASSWORD: ${{ secrets.OYM_PASSWORD }}
+        run: echo "Environment variables for Maven credentials set."
+
+      - name: Setup Maven credentials
+        run: |
+          if [[ -f "maven-settings.xml" ]]; then
+            sed -i "s/{OYM_USERNAME}/$OYM_USERNAME/g" maven-settings.xml
+            sed -i "s/{OYM_PASSWORD}/$OYM_PASSWORD/g" maven-settings.xml
+          else
+            echo "maven-settings.xml file not found!"
+            exit 1
+          fi
 
       - name: Running tests and deploying
         run: |
